services:
  - type: web
    name: beauty-battle
    env: docker
    region: frankfurt
    plan: free
    healthCheckPath: /
    buildCommand: |
      # Создаем необходимые директории
      mkdir -p public/uploads/{photos,videos,thumbnails} cache logs public/errors
      # Копируем SSL сертификат
      mkdir -p /var/www/.postgresql
      cp /etc/ssl/certs/ca-certificates.crt /var/www/.postgresql/root.crt
      # Собираем Docker образ
      docker build -t beauty-battle .
    startCommand: docker run -p $PORT:8080 beauty-battle
    envVars:
      - key: PORT
        value: 8080
      - key: DB_HOST
        fromDatabase:
          name: facemash-battle-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: facemash-battle-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: facemash-battle-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: facemash-battle-db
          property: password
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_BOT_USERNAME
        sync: false
      - key: APP_URL
        sync: false
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
    disk:
      name: data
      mountPath: /var/www/html/public/uploads
      sizeGB: 1

databases:
  - name: facemash-battle-db
    region: frankfurt
    plan: free
    ipAllowList: []
    postDeploy: |
      # Инициализация базы данных
      php scripts/init_render_db.php

# Настройка постоянного хранилища
disks:
  - name: data
    region: frankfurt
    plan: free
    sizeGB: 1
    mountPath: /var/www/html/public/uploads 