services:
  - type: web
    name: beauty-battle
    env: docker
    region: oregon
    plan: free
    healthCheckPath: /
    buildCommand: docker build -t beauty-battle .
    startCommand: docker run --init -p 8080:8080 beauty-battle
    envVars:
      - key: PORT
        value: 8080
      - key: DB_HOST
        fromDatabase:
          name: facemash-battle-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: facemash-battle-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: facemash-battle-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: facemash-battle-db
          property: password
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_BOT_USERNAME
        sync: false
      - key: APP_URL
        sync: false

databases:
  - name: facemash-battle-db
    region: oregon
    plan: free
    ipAllowList: [] 