services:
  - type: web
    name: beauty-battle
    env: docker
    region: frankfurt
    plan: free
    healthCheckPath: /health.php
    buildCommand: docker build -t beauty-battle .
    startCommand: docker run -p $PORT:8080 beauty-battle
    envVars:
      - key: PORT
        value: 8080
      - key: DB_HOST
        fromDatabase:
          name: beauty-battle-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: beauty-battle-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: beauty-battle-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: beauty-battle-db
          property: password
      - key: APP_URL
        value: https://beauty-battle.onrender.com
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: UPLOAD_MAX_SIZE
        value: 10485760  # 10MB в байтах
      - key: IMAGE_QUALITY
        value: 80
      - key: SCRIPT_TIMEOUT
        value: 60
      - key: SESSION_LIFETIME
        value: 7200
      - key: CSRF_TOKEN_LIFETIME
        value: 3600
    disk:
      name: beauty-battle-uploads
      mountPath: /var/www/html/public/uploads
      sizeGB: 1
    healthCheck:
      httpPath: /health.php
      port: 8080
      initialDelaySeconds: 30
      periodSeconds: 15
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 3

databases:
  - name: beauty-battle-db
    region: frankfurt
    plan: free
    ipAllowList: [] 