services:
  - type: web
    name: beauty-battle
    env: php
    buildCommand: |
      composer install
      npm install
    startCommand: php -S 0.0.0.0:$PORT -t public/
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false 