services:
  - type: web
    name: beauty-battle
    env: docker
    region: frankfurt
    plan: free
    healthCheckPath: /
    buildCommand: docker build -t beauty-battle .
    startCommand: docker run --init -p 8080:8080 beauty-battle
    envVars:
      - key: PORT
        value: 8080
      - key: DB_HOST
        value: dpg-curhd59u0jms73bu6n1g-a.frankfurt-postgres.render.com
      - key: DB_NAME
        value: facemash_battle
      - key: DB_USER
        value: facemash_battle_user
      - key: DB_PASSWORD
        value: 15pikTGIS74injOhP3Cjt171vbQOFuZA
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_BOT_USERNAME
        sync: false
      - key: APP_URL
        sync: false

databases:
  - name: facemash-battle-db
    region: frankfurt
    plan: free
    ipAllowList: [] 